### ISSUE TITLE
esp8266

### ISSUE THREAD

**Issue by adbensi** [stevemarple/RTCx#2]
Nice library! To build on the esp8266 I change

//#include <avr/pgmspace.h> to

#if ARDUINO >= 100
 #include <Arduino.h>
#else
 #include <WProgram.h>
#endif

Best Regards,
Alexandre Bensi

**Comment by jae686** [comment]
Thank you @adbensi , it fixed for me :)

**Comment by stevemarple** [comment]
Version 1.0.5 and its example should now compile cleanly for ESP8266.

**Comment by LAKSHYAJAIN** [comment]
Please help!
How to use this library for esp8266
