### ISSUE TITLE
Bitmask for wday in RTCx.cpp

### ISSUE THREAD

**Issue by NABarnes** [stevemarple/RTCx#3]
Hi,

Thank you for the library.

I'm just getting into programming and have spent a while trying to work out why I was getting strange results. I think it looks like the following line in RTCx.cpp:

`tm->tm_wday = (Wire.read() & 0x03) - 1; // Clock uses [1..7]`

should be:

`tm->tm_wday = (Wire.read() & 0x07) - 1; // Clock uses [1..7]`

As the day field is three bits long and not two. If I am wrong, please accept my apologies.

mktime() then ignores the tm_wday read and redefines it. I'm not sure if this was a workaround for the incorrect value read or for some other reason. If running mktime() after readClock() is mandatory/advised, then could/should a call be made to mktime() from within readClock()?

Many thanks,

Nicholas.

**Comment by stevemarple** [comment]
Hi Nicholas,
it seems that you are right and it should be masked with  0x07, not 0x03. I've pushed a fix (c069f469b4e9023b98195d0a1151e93bf27f228d) which should resolve this but I'm not able to test it right now. The latest version, [1.0.4](https://github.com/stevemarple/RTCx/tree/v1.0.4), contains this fix. Thanks for alerting me - please let me know if you agree that this resolves the problem (or not).

The standard behaviour of the `mktime` library function is to ignore both day of week and day of year (see https://linux.die.net/man/3/mktime), computing both from the supplied date. My `mktime` function follows the same behaviour.

It is not necessary to call `mktime` after `readClock`; `mktime` can be given any argument, it does not need to be the current time.
